"""empty message

Revision ID: 2d7ee9298bfc
Revises: f12c2f06a973
Create Date: 2022-03-27 21:44:48.616448

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d7ee9298bfc'
down_revision = 'f12c2f06a973'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app', sa.Column('date_published', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_app_date_published'), 'app', ['date_published'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_app_date_published'), table_name='app')
    op.drop_column('app', 'date_published')
    # ### end Alembic commands ###
