"""empty message

Revision ID: b006e3ee3590
Revises: 2d7ee9298bfc
Create Date: 2022-03-27 21:50:07.802312

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b006e3ee3590'
down_revision = '2d7ee9298bfc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app', sa.Column('publisher', sa.Integer(), nullable=True))
    op.add_column('app', sa.Column('version', sa.String(length=10), nullable=True))
    op.add_column('app', sa.Column('weight', sa.String(length=20), nullable=True))
    op.add_column('app', sa.Column('tags', sa.JSON(), nullable=True))
    op.add_column('app', sa.Column('screenshots', sa.JSON(), nullable=True))
    op.add_column('app', sa.Column('big_icon', sa.String(length=200), nullable=True))
    op.add_column('app', sa.Column('small_icon', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('app', 'small_icon')
    op.drop_column('app', 'big_icon')
    op.drop_column('app', 'screenshots')
    op.drop_column('app', 'tags')
    op.drop_column('app', 'weight')
    op.drop_column('app', 'version')
    op.drop_column('app', 'publisher')
    # ### end Alembic commands ###
