"""empty message

Revision ID: ea0018c29e51
Revises: 52cae050f979
Create Date: 2022-03-27 15:34:35.893961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea0018c29e51'
down_revision = '52cae050f979'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(length=3000), nullable=True),
    sa.Column('download_link', sa.String(length=3000), nullable=True),
    sa.Column('is_published', sa.Integer(), nullable=True),
    sa.Column('downloads', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('user', sa.Column('apps', sa.JSON(), nullable=True))
    op.add_column('user', sa.Column('favourites', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'favourites')
    op.drop_column('user', 'apps')
    op.drop_table('app')
    # ### end Alembic commands ###
