"""empty message

Revision ID: f12c2f06a973
Revises: ea0018c29e51
Create Date: 2022-03-27 21:40:15.951025

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f12c2f06a973'
down_revision = 'ea0018c29e51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_banned', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_banned')
    # ### end Alembic commands ###
